# 通用设置
gpu : '0'
reset : false
mean : [31.753, 51.583, 56.864]  # BGR
std : [14.795, 35.488, 44.959]  # BGR

# 训练需要修改参数
train_data_path : 'D:\Project\PYTHON\classification\data\train.txt'
val_data_path : 'D:\Project\PYTHON\classification\data\valid.txt'
classes : ['C1F', 'C2F', 'C3F', 'C4F', 'Q', 'Z'] # 如果为空则默认为train_data_dir中的类别
network : 'resnet50'   # [resnet50,mobilenetv2]
multi_label : false
focal_loss : true
alpha : [0.5]
gamma : 2

reload_weights_path : ''
 
learning_rate_base : 0.0001
batch_size : 4
img_height : 384
img_width : 1152
channels : 3
epochs : 40
log_dir : 'log'


train_augdata_dir : ~ # 'aug/train'
val_augdata_dir : ~ # 'aug/val'

imgaug_params : {
  scale : ~,
  translate_percent : {x: [-0.05, 0.05], y: [-0.01, 0.01]},
  rotate : [-10, 10],
  shear : ~,
  flip_lr : 0.5,
  flip_ud : 0.5,
  crop : ~,
  multiply : [0.8, 1.2],
  gaussian_noise : [0, 2.55],
  gaussian_blur : [0, 1.0],
  linear_contrast : ~
}

#转换模型需要修改参数
convert_weights_path : 'log\resnet50-ep009-loss0.118-val_loss0.125.h5'
pb_path : '0929-tobacco.scidl'


# 测试图片需要修改参数
test_data_dir : '/data/jiangwei/中烟/test'
mode : 'pb'  # 'pb' or 'weights'
test_weights_path : 'log-0927/last.h5'
test_pb_path : 'test.pb'
is_save_result : true
threshold : [0.5]


# 内置参数
test_result_dir : 'result'



