train_data : 'D:\Project\PYTHON\classification\data\train.txt'
valid_data : 'D:\Project\PYTHON\classification\data\valid.txt'

class_info : 'D:\Project\PYTHON\classification\data\class.txt'
project_dir : 'D:\Project\PYTHON\classification\log'

network : 'resnet50'
weights : 'D:\Project\PYTHON\viewer\classification\pretrain_model\resnet.ckpt'
loss : categorical_crossentropy

transfer : false
train_all : true
epochs : 100
height : 224
width : 224
lr : 0.0001
batch_size : 32
workers : 2

scale : [0.8, 1.2]
translate_percent_x : [0, 0.05]
translate_percent_y : [0, 0.05]
rotate : [-180, 180]
shear : [-10, 10]
flip_lr : 0.5
flip_ud : 0.5
crop : [0, 0.1]
multiply : ~
gaussian_noise : ~
gaussian_blur : ~
linear_contrast : ~

port : 0